name: Build and Test

on:
  push:

env:
  GO_VERSION: 1.19

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - uses: actions/cache@v3
        with:
          path: |
            libsignal/Cargo.toml
            libsignal/libsignal-ffi.h
            libsignal/target/release/libsignal_ffi.a
          key: ${{ hashFiles('./Makefile') }}

      - name: Make libsignal/libsignal-ffi.h
        run: make

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - uses: actions/cache@v3
        with:
          path: |
            libsignal/Cargo.toml
            libsignal/libsignal-ffi.h
            libsignal/target/release/libsignal_ffi.a
          key: ${{ hashFiles('./Makefile') }}

      - name: Install Dependencies
        run: |
          go install -v github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Make libsignal/libsignal-ffi.h
        run: make

      - name: Run tests
        run: |
          go test -v -json ./... -cover | gotestfmt
